name: PR creation

on:
  workflow_dispatch:

permissions:
  contents: write #needed
  packages: read
  actions: read
  id-token: write
  issues: write
  pull-requests: write #needed

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
            token: ${{ secrets.GITHUB_TOKEN }}

      - name: create pull request
        run: gh pr create -B main -H feature-branch-pr-creation --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action' --dry-run --web --draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}