name: PR review approved

on:
  workflow_call

permissions:
  contents: read
  packages: read
  actions: read
  id-token: write
  issues: write

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 5

      - name: do something
        run: exit 1