name: Merge To Develop

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: read
  actions: read
  id-token: write
  issues: write

jobs:
  validate-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: startsWith(github.head_ref, 'first-')
        run: |
          echo "ERROR: You cannot open a PR to main from a feature branch."
          exit 1