name: PR review approved

on:
  pull_request_review:
    types: [ submitted ]

permissions:
  contents: read
  packages: read
  actions: read
  id-token: write
  issues: write

jobs:
  check_condition:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    outputs:
      tf_related: ${{ steps.filter.outputs.tf_related }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 5

      - name: Gather modified files
        uses: dorny/paths-filter@v3
        id: filter
        with:
          list-files: json
          filters: |
              tf_related:
                - 'dbt/dbt_snowflake_dwh/models/**'
#                - 'aws/terraform/**'
#                - 'dbt/dbt_snowflake_dwh/Dockerfile'
#                - 'dbt/dbt_snowflake_dwh/poetry.lock'
#                - 'dbt/dbt_snowflake_dwh/pyproject.toml'

  deploy-tf-dev:
    runs-on: ubuntu-latest
    needs: check_condition
    if: ${{ needs.check_condition.outputs.tf_related == 'true' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

  # Only run if previous step failed
  deploy-tf-dev-from-develop:
    if: ${{ needs.check_condition.outputs.tf_related == 'true' && failure() }}
    needs: check_condition
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: do stuff
        run: gh workflow run deploy_aws_branch.yml --ref develop --raw-field run-DBT-Docker-Step-flag=true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
