name: PR review approved

on:
  pull_request:
    branches:
      - develop

permissions:
  contents: read
  packages: read
  actions: read
  id-token: write
  issues: write

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
      - name: do something
        run: sleep 30