name: PR review approved

on:
  pull_request_review:
    types: [ submitted ]

permissions:
  contents: read
  packages: read
  actions: read
  id-token: write
  issues: write

jobs:
  run_deploy_TF_dev:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 5

      - name: Gather modified files
        uses: dorny/paths-filter@v3
        id: filter
        with:
          list-files: json
          filters: |
              tf_related:
                - 'aws/terraform/**'
                - 'dbt/dbt_snowflake_dwh/Dockerfile'
                - 'dbt/dbt_snowflake_dwh/poetry.lock'
                - 'dbt/dbt_snowflake_dwh/pyproject.toml'

      - name: Trigger deploy AWS
        if: steps.filter.outputs.tf_related == 'true'
        run: gh workflow run deploy_aws_branch.yml --ref ${{ github.event.pull_request.base.ref }} --raw-field run-DBT-Docker-Step-flag=true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: IF FAIL - re-trigger with develop
        if: steps.filter.outputs.tf_related == 'true'
        run: gh workflow run deploy_aws_branch.yml --ref main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
