name: PR review approved

on:
  pull_request_review:
    types: [ submitted ]

permissions:
  contents: read
  packages: read
  actions: read
  id-token: write
  issues: write

jobs:
  run_deploy_TF_dev:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 5

      - name: Gather modified files
        uses: dorny/paths-filter@v3
        id: filter
        with:
          list-files: json
          filters: |
              tf_related:
                - 'aws/terraform/**'
                - 'dbt/dbt_snowflake_dwh/Dockerfile'
                - 'dbt/dbt_snowflake_dwh/poetry.lock'
                - 'dbt/dbt_snowflake_dwh/pyproject.toml'

      - name: Trigger deploy AWS with the feature branch
        id: trigger-TF-from-feature-branch

        if: steps.filter.outputs.tf_related == 'true'
        uses: |
          actions/checkout@v4
          ./.github/workflows/deploy_resources.yml

      # Only run if previous step failed
      - name: Trigger deploy AWS with develop
        if: steps.filter.outputs.tf_related == 'true' && ${{ success() || failure() }}
        run: gh workflow run deploy_aws_branch.yml --ref develop --raw-field run-DBT-Docker-Step-flag=true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
